### Python练习实例41
#### 题目：
    模仿静态变量的用法。
#### 程序分析：
    无。

In [1]:
def varfunc():
    var = 0
    print("var = %d" % var)
    var += 1

for i in range(3):
    varfunc()
        
# 类的属性
# 作为类的一个属性
class Static:
    StaticVar = 5
    def varfunc(self):
        self.StaticVar += 1
        print(self.StaticVar)
        
print(Static.StaticVar)
a = Static()
for i in range(3):
    a.varfunc()

var = 0
var = 0
var = 0
5
6
7
8


### Python练习实例42
#### 题目：
    学习使用auto定义变量的方法。
#### 程序分析：
    没有auto关键字，使用变量作用域举例。

In [2]:
num = 2
def autofunc():
    num = 1
    print("internal block num = %d" % num)
    
    num += 1
for i in range(3):
    print("The num = %d" % num)
    num += 1 
    autofunc()

The num = 2
internal block num = 1
The num = 3
internal block num = 1
The num = 4
internal block num = 1


### Python练习实例43
#### 题目：
    模仿静态函数（static）的另一案例。
#### 程序分析：
    演示一个python作用域的使用方法。

In [3]:
class Num:
    nNum = 1
    def inc(self):
        self.nNum += 1
        print("nNum = %d" % nNum)


nNum = 2
inst = Num()
for i in range(3):
    nNum += 1
    print("The num = %d" % nNum)
    inst.inc()

The num = 3
nNum = 3
The num = 4
nNum = 4
The num = 5
nNum = 5


### Python练习实例44
#### 题目：
    两个 3 行 3 列的矩阵，实现其对应位置的数据相加，并返回一个新矩阵.
    X = [[12,7,3],
        [4 ,5,6],
        [7 ,8,9]]

    Y = [[5,8,1],
        [6,7,3],
        [4,5,9]]
#### 程序分析：
    创建一个新的 3 行 3 列的矩阵，使用 for 迭代并取出 X 和 Y 矩阵中对应位置的值，相加后放到新矩阵的对应位置中。

In [4]:
# 方法一
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
 
Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]
 
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]
 
# 迭代输出行
for i in range(len(X)):
   # 迭代输出列
   for j in range(len(X[0])):
       result[i][j] = X[i][j] + Y[i][j]
 
for r in result:
   print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [5]:
# 方法二
import numpy as np
a=np.random.randint(0,100,9).reshape(3,3)
b=np.random.randint(0,100,9).reshape(3,3)

print(a+b)

[[ 88  78  72]
 [178 151  73]
 [ 68 178  31]]


### Python练习实例45
#### 题目：
    计算1到100之和。
#### 程序分析：
    无。

In [6]:
# 方法一
tmp = 0
for i in range(1, 101):
    tmp +=i
print("The sum is %d" % tmp)

The sum is 5050


In [7]:
# 方法二
print(sum(range(1, 101)))

5050


In [8]:
# 方法三
from functools import reduce
reduce(lambda x, y: x + y, range(1, 101))

5050

### Python练习实例46
#### 题目：
    求输入数字的平方，如果平方运算后小于50则退出。
#### 程序分析：
    无。

In [9]:
while 1:
    n=int(input("请输入一个数字:"))
    print("运算结果为: %d" % (n**2))
    if n**2 < 50:
        break
    else:
        print("请继续输入")

请输入一个数字:88
运算结果为: 7744
请继续输入
请输入一个数字:20
运算结果为: 400
请继续输入
请输入一个数字:5
运算结果为: 25


### Python练习实例47
#### 题目：
    两个变量值互换。
#### 程序分析：
    无。

In [10]:
def exchange(a, b):
    a, b = b, a
    return a, b

if __name__ == "__main__":
    x = 10
    y = 20
    print("x = %d, y = %d" % (x, y))
    x, y = exchange(x, y)
    print("x = %d, y = %d" % (x, y))

x = 10, y = 20
x = 20, y = 10


### Python练习实例48
#### 题目：
    数字比较
#### 程序分析：
    无。

In [11]:
# 方法一 
i = 10
j = 20
if i > j:
    print("%d 大于 %d" % (i, j))
elif i < j:
    print("%d 小于 %d" % (i, j))
elif i == j:
    print("%d 等于 %d" % (i, j))
else:
    print("未知！！！")

10 小于 20


In [12]:
# 方法二 
def compare(num1, num2):
    if num1 > num2:
        print("%s大于%s" % (num1, num2))
    elif num2 > num1:
        print("%s大于%s" % (num2, num1))
    else:
        print("%s等于%s" % (num1, num2))

a = input("请输入第一个数字:")
b = input("请输入第二个数字:")
compare(a, b)

请输入第一个数字:8
请输入第二个数字:11
8大于11


In [13]:
# 方法三
def compare(a,b):
    maxSum = max(a,b)
    minSum = min(a,b)
    print('%s大于%s'%(maxSum,minSum))
    
a = input("请输入第一个数字:")
b = input("请输入第二个数字:")
compare(a,b)

请输入第一个数字:2
请输入第二个数字:1
2大于1


### Python练习实例49
#### 题目：
    使用lambda创建匿名函数。
#### 程序分析：
    无。

In [14]:
# 案例一
MAXIMUM = lambda x,y :  (x > y) * x + (x < y) * y
MINIMUM = lambda x,y :  (x > y) * y + (x < y) * x
 
a = 10
b = 20
print( 'The larger one is %d' % MAXIMUM(a,b))
print( 'The lower one is %d' % MINIMUM(a,b))

The larger one is 20
The lower one is 10


In [15]:
# 实例二
func=lambda x,y: x + y
x,y=eval(input('请输入两个数字，并以逗号分隔：\n'))
print(func(x,y))

请输入两个数字，并以逗号分隔：
5,13
18


### Python练习实例50
#### 题目：
    输出一个随机数。
#### 程序分析：
    使用random模块。

In [16]:
import random


x,y=eval(input('请输入两个数字，并以逗号分隔：\n'))

print(random.random())          # 输入0-1之间的随机数
print(random.uniform(x, y))     # 生成指定范围的随机小数
print(random.randint(x, y))     # 输出10-20之间的随机整数
print(random.choice([x for x in range(0, 100)]))  # 在列表中随机抽取一个数

请输入两个数字，并以逗号分隔：
5,55
0.09548784606364191
28.99401115130768
5
9
